/* automatically generated by rust-bindgen 0.72.1 */

use libc::FILE;

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val { byte | mask } else { byte & !mask }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
pub type cleri_grammar_t = cleri_grammar_s;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
    _unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 3usize]>,
    pub _short_backupbuf: [::std::os::raw::c_char; 1usize],
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_schar,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub _codecvt: *mut _IO_codecvt,
    pub _wide_data: *mut _IO_wide_data,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut ::std::os::raw::c_void,
    pub _prevchain: *mut *mut _IO_FILE,
    pub _mode: ::std::os::raw::c_int,
    pub _unused3: ::std::os::raw::c_int,
    pub _total_written: __uint64_t,
    pub _unused2: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _IO_FILE"][::std::mem::size_of::<_IO_FILE>() - 216usize];
    ["Alignment of _IO_FILE"][::std::mem::align_of::<_IO_FILE>() - 8usize];
    ["Offset of field: _IO_FILE::_flags"][::std::mem::offset_of!(_IO_FILE, _flags) - 0usize];
    ["Offset of field: _IO_FILE::_IO_read_ptr"]
        [::std::mem::offset_of!(_IO_FILE, _IO_read_ptr) - 8usize];
    ["Offset of field: _IO_FILE::_IO_read_end"]
        [::std::mem::offset_of!(_IO_FILE, _IO_read_end) - 16usize];
    ["Offset of field: _IO_FILE::_IO_read_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_read_base) - 24usize];
    ["Offset of field: _IO_FILE::_IO_write_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_write_base) - 32usize];
    ["Offset of field: _IO_FILE::_IO_write_ptr"]
        [::std::mem::offset_of!(_IO_FILE, _IO_write_ptr) - 40usize];
    ["Offset of field: _IO_FILE::_IO_write_end"]
        [::std::mem::offset_of!(_IO_FILE, _IO_write_end) - 48usize];
    ["Offset of field: _IO_FILE::_IO_buf_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_buf_base) - 56usize];
    ["Offset of field: _IO_FILE::_IO_buf_end"]
        [::std::mem::offset_of!(_IO_FILE, _IO_buf_end) - 64usize];
    ["Offset of field: _IO_FILE::_IO_save_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_save_base) - 72usize];
    ["Offset of field: _IO_FILE::_IO_backup_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_backup_base) - 80usize];
    ["Offset of field: _IO_FILE::_IO_save_end"]
        [::std::mem::offset_of!(_IO_FILE, _IO_save_end) - 88usize];
    ["Offset of field: _IO_FILE::_markers"][::std::mem::offset_of!(_IO_FILE, _markers) - 96usize];
    ["Offset of field: _IO_FILE::_chain"][::std::mem::offset_of!(_IO_FILE, _chain) - 104usize];
    ["Offset of field: _IO_FILE::_fileno"][::std::mem::offset_of!(_IO_FILE, _fileno) - 112usize];
    ["Offset of field: _IO_FILE::_short_backupbuf"]
        [::std::mem::offset_of!(_IO_FILE, _short_backupbuf) - 119usize];
    ["Offset of field: _IO_FILE::_old_offset"]
        [::std::mem::offset_of!(_IO_FILE, _old_offset) - 120usize];
    ["Offset of field: _IO_FILE::_cur_column"]
        [::std::mem::offset_of!(_IO_FILE, _cur_column) - 128usize];
    ["Offset of field: _IO_FILE::_vtable_offset"]
        [::std::mem::offset_of!(_IO_FILE, _vtable_offset) - 130usize];
    ["Offset of field: _IO_FILE::_shortbuf"]
        [::std::mem::offset_of!(_IO_FILE, _shortbuf) - 131usize];
    ["Offset of field: _IO_FILE::_lock"][::std::mem::offset_of!(_IO_FILE, _lock) - 136usize];
    ["Offset of field: _IO_FILE::_offset"][::std::mem::offset_of!(_IO_FILE, _offset) - 144usize];
    ["Offset of field: _IO_FILE::_codecvt"][::std::mem::offset_of!(_IO_FILE, _codecvt) - 152usize];
    ["Offset of field: _IO_FILE::_wide_data"]
        [::std::mem::offset_of!(_IO_FILE, _wide_data) - 160usize];
    ["Offset of field: _IO_FILE::_freeres_list"]
        [::std::mem::offset_of!(_IO_FILE, _freeres_list) - 168usize];
    ["Offset of field: _IO_FILE::_freeres_buf"]
        [::std::mem::offset_of!(_IO_FILE, _freeres_buf) - 176usize];
    ["Offset of field: _IO_FILE::_prevchain"]
        [::std::mem::offset_of!(_IO_FILE, _prevchain) - 184usize];
    ["Offset of field: _IO_FILE::_mode"][::std::mem::offset_of!(_IO_FILE, _mode) - 192usize];
    ["Offset of field: _IO_FILE::_unused3"][::std::mem::offset_of!(_IO_FILE, _unused3) - 196usize];
    ["Offset of field: _IO_FILE::_total_written"]
        [::std::mem::offset_of!(_IO_FILE, _total_written) - 200usize];
    ["Offset of field: _IO_FILE::_unused2"][::std::mem::offset_of!(_IO_FILE, _unused2) - 208usize];
};
impl _IO_FILE {
    #[inline]
    pub fn _flags2(&self) -> ::std::os::raw::c_int {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 24u8) as u32) }
    }
    #[inline]
    pub fn set__flags2(&mut self, val: ::std::os::raw::c_int) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 24u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn _flags2_raw(this: *const Self) -> ::std::os::raw::c_int {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 3usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                24u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set__flags2_raw(this: *mut Self, val: ::std::os::raw::c_int) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 3usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                24u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(_flags2: ::std::os::raw::c_int) -> __BindgenBitfieldUnit<[u8; 3usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 3usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 24u8, {
            let _flags2: u32 = unsafe { ::std::mem::transmute(_flags2) };
            _flags2 as u64
        });
        __bindgen_bitfield_unit
    }
}
pub const data_type_data_none: data_type = 0;
pub const data_type_data_i: data_type = 1;
pub const data_type_data_f: data_type = 2;
pub const data_type_data_b: data_type = 3;
pub const data_type_data_s: data_type = 4;
pub type data_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct data_list_struct {
    pub data: data_list_struct__bindgen_ty_1,
    pub data_t: data_type,
    pub next: *mut data_list_struct,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union data_list_struct__bindgen_ty_1 {
    pub i: ::std::os::raw::c_int,
    pub f: f64,
    pub s: *mut ::std::os::raw::c_char,
    pub b: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of data_list_struct__bindgen_ty_1"]
        [::std::mem::size_of::<data_list_struct__bindgen_ty_1>() - 8usize];
    ["Alignment of data_list_struct__bindgen_ty_1"]
        [::std::mem::align_of::<data_list_struct__bindgen_ty_1>() - 8usize];
    ["Offset of field: data_list_struct__bindgen_ty_1::i"]
        [::std::mem::offset_of!(data_list_struct__bindgen_ty_1, i) - 0usize];
    ["Offset of field: data_list_struct__bindgen_ty_1::f"]
        [::std::mem::offset_of!(data_list_struct__bindgen_ty_1, f) - 0usize];
    ["Offset of field: data_list_struct__bindgen_ty_1::s"]
        [::std::mem::offset_of!(data_list_struct__bindgen_ty_1, s) - 0usize];
    ["Offset of field: data_list_struct__bindgen_ty_1::b"]
        [::std::mem::offset_of!(data_list_struct__bindgen_ty_1, b) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of data_list_struct"][::std::mem::size_of::<data_list_struct>() - 24usize];
    ["Alignment of data_list_struct"][::std::mem::align_of::<data_list_struct>() - 8usize];
    ["Offset of field: data_list_struct::data"]
        [::std::mem::offset_of!(data_list_struct, data) - 0usize];
    ["Offset of field: data_list_struct::data_t"]
        [::std::mem::offset_of!(data_list_struct, data_t) - 8usize];
    ["Offset of field: data_list_struct::next"]
        [::std::mem::offset_of!(data_list_struct, next) - 16usize];
};
pub type DataLinkedList = data_list_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dict_entry_struct {
    pub key: *mut ::std::os::raw::c_char,
    pub data: *mut ::std::os::raw::c_void,
    pub data_t: data_type,
    pub nrows: ::std::os::raw::c_int,
    pub ncols: ::std::os::raw::c_int,
    pub next: *mut dict_entry_struct,
    pub first_data_ll: *mut DataLinkedList,
    pub last_data_ll: *mut DataLinkedList,
    pub n_in_row: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dict_entry_struct"][::std::mem::size_of::<dict_entry_struct>() - 64usize];
    ["Alignment of dict_entry_struct"][::std::mem::align_of::<dict_entry_struct>() - 8usize];
    ["Offset of field: dict_entry_struct::key"]
        [::std::mem::offset_of!(dict_entry_struct, key) - 0usize];
    ["Offset of field: dict_entry_struct::data"]
        [::std::mem::offset_of!(dict_entry_struct, data) - 8usize];
    ["Offset of field: dict_entry_struct::data_t"]
        [::std::mem::offset_of!(dict_entry_struct, data_t) - 16usize];
    ["Offset of field: dict_entry_struct::nrows"]
        [::std::mem::offset_of!(dict_entry_struct, nrows) - 20usize];
    ["Offset of field: dict_entry_struct::ncols"]
        [::std::mem::offset_of!(dict_entry_struct, ncols) - 24usize];
    ["Offset of field: dict_entry_struct::next"]
        [::std::mem::offset_of!(dict_entry_struct, next) - 32usize];
    ["Offset of field: dict_entry_struct::first_data_ll"]
        [::std::mem::offset_of!(dict_entry_struct, first_data_ll) - 40usize];
    ["Offset of field: dict_entry_struct::last_data_ll"]
        [::std::mem::offset_of!(dict_entry_struct, last_data_ll) - 48usize];
    ["Offset of field: dict_entry_struct::n_in_row"]
        [::std::mem::offset_of!(dict_entry_struct, n_in_row) - 56usize];
};
pub type DictEntry = dict_entry_struct;
unsafe extern "C" {
    pub fn extxyz_read_ll(
        kv_grammar: *mut cleri_grammar_t,
        fp: *mut FILE,
        nat: *mut ::std::os::raw::c_int,
        info: *mut *mut DictEntry,
        arrays: *mut *mut DictEntry,
        comment: *mut ::std::os::raw::c_char,
        error_message: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn extxyz_write_ll(
        fp: *mut FILE,
        nat: ::std::os::raw::c_int,
        info: *mut DictEntry,
        arrays: *mut DictEntry,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn extxyz_malloc(nbytes: usize) -> *mut ::std::os::raw::c_void;
}
pub type cleri_t = cleri_s;
pub type cleri_olist_t = cleri_olist_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_olist_s {
    pub cl_obj: *mut cleri_t,
    pub next: *mut cleri_olist_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_olist_s"][::std::mem::size_of::<cleri_olist_s>() - 16usize];
    ["Alignment of cleri_olist_s"][::std::mem::align_of::<cleri_olist_s>() - 8usize];
    ["Offset of field: cleri_olist_s::cl_obj"]
        [::std::mem::offset_of!(cleri_olist_s, cl_obj) - 0usize];
    ["Offset of field: cleri_olist_s::next"][::std::mem::offset_of!(cleri_olist_s, next) - 8usize];
};
pub type cleri_exp_modes_t = cleri_exp_modes_s;
pub type cleri_expecting_t = cleri_expecting_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_exp_modes_s {
    pub mode: ::std::os::raw::c_int,
    pub str_: *const ::std::os::raw::c_char,
    pub next: *mut cleri_exp_modes_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_exp_modes_s"][::std::mem::size_of::<cleri_exp_modes_s>() - 24usize];
    ["Alignment of cleri_exp_modes_s"][::std::mem::align_of::<cleri_exp_modes_s>() - 8usize];
    ["Offset of field: cleri_exp_modes_s::mode"]
        [::std::mem::offset_of!(cleri_exp_modes_s, mode) - 0usize];
    ["Offset of field: cleri_exp_modes_s::str_"]
        [::std::mem::offset_of!(cleri_exp_modes_s, str_) - 8usize];
    ["Offset of field: cleri_exp_modes_s::next"]
        [::std::mem::offset_of!(cleri_exp_modes_s, next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_expecting_s {
    pub str_: *const ::std::os::raw::c_char,
    pub required: *mut cleri_olist_t,
    pub optional: *mut cleri_olist_t,
    pub modes: *mut cleri_exp_modes_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_expecting_s"][::std::mem::size_of::<cleri_expecting_s>() - 32usize];
    ["Alignment of cleri_expecting_s"][::std::mem::align_of::<cleri_expecting_s>() - 8usize];
    ["Offset of field: cleri_expecting_s::str_"]
        [::std::mem::offset_of!(cleri_expecting_s, str_) - 0usize];
    ["Offset of field: cleri_expecting_s::required"]
        [::std::mem::offset_of!(cleri_expecting_s, required) - 8usize];
    ["Offset of field: cleri_expecting_s::optional"]
        [::std::mem::offset_of!(cleri_expecting_s, optional) - 16usize];
    ["Offset of field: cleri_expecting_s::modes"]
        [::std::mem::offset_of!(cleri_expecting_s, modes) - 24usize];
};
pub type cleri_keyword_t = cleri_keyword_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_keyword_s {
    pub keyword: *const ::std::os::raw::c_char,
    pub ign_case: ::std::os::raw::c_int,
    pub len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_keyword_s"][::std::mem::size_of::<cleri_keyword_s>() - 24usize];
    ["Alignment of cleri_keyword_s"][::std::mem::align_of::<cleri_keyword_s>() - 8usize];
    ["Offset of field: cleri_keyword_s::keyword"]
        [::std::mem::offset_of!(cleri_keyword_s, keyword) - 0usize];
    ["Offset of field: cleri_keyword_s::ign_case"]
        [::std::mem::offset_of!(cleri_keyword_s, ign_case) - 8usize];
    ["Offset of field: cleri_keyword_s::len"]
        [::std::mem::offset_of!(cleri_keyword_s, len) - 16usize];
};
pub type cleri_sequence_t = cleri_sequence_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_sequence_s {
    pub olist: *mut cleri_olist_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_sequence_s"][::std::mem::size_of::<cleri_sequence_s>() - 8usize];
    ["Alignment of cleri_sequence_s"][::std::mem::align_of::<cleri_sequence_s>() - 8usize];
    ["Offset of field: cleri_sequence_s::olist"]
        [::std::mem::offset_of!(cleri_sequence_s, olist) - 0usize];
};
pub type cleri_optional_t = cleri_optional_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_optional_s {
    pub cl_obj: *mut cleri_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_optional_s"][::std::mem::size_of::<cleri_optional_s>() - 8usize];
    ["Alignment of cleri_optional_s"][::std::mem::align_of::<cleri_optional_s>() - 8usize];
    ["Offset of field: cleri_optional_s::cl_obj"]
        [::std::mem::offset_of!(cleri_optional_s, cl_obj) - 0usize];
};
pub type cleri_choice_t = cleri_choice_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_choice_s {
    pub most_greedy: ::std::os::raw::c_int,
    pub olist: *mut cleri_olist_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_choice_s"][::std::mem::size_of::<cleri_choice_s>() - 16usize];
    ["Alignment of cleri_choice_s"][::std::mem::align_of::<cleri_choice_s>() - 8usize];
    ["Offset of field: cleri_choice_s::most_greedy"]
        [::std::mem::offset_of!(cleri_choice_s, most_greedy) - 0usize];
    ["Offset of field: cleri_choice_s::olist"]
        [::std::mem::offset_of!(cleri_choice_s, olist) - 8usize];
};
pub type cleri_dup_t = cleri_dup_s;
pub type cleri_list_t = cleri_list_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_list_s {
    pub cl_obj: *mut cleri_t,
    pub delimiter: *mut cleri_t,
    pub min: usize,
    pub max: usize,
    pub opt_closing: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_list_s"][::std::mem::size_of::<cleri_list_s>() - 40usize];
    ["Alignment of cleri_list_s"][::std::mem::align_of::<cleri_list_s>() - 8usize];
    ["Offset of field: cleri_list_s::cl_obj"]
        [::std::mem::offset_of!(cleri_list_s, cl_obj) - 0usize];
    ["Offset of field: cleri_list_s::delimiter"]
        [::std::mem::offset_of!(cleri_list_s, delimiter) - 8usize];
    ["Offset of field: cleri_list_s::min"][::std::mem::offset_of!(cleri_list_s, min) - 16usize];
    ["Offset of field: cleri_list_s::max"][::std::mem::offset_of!(cleri_list_s, max) - 24usize];
    ["Offset of field: cleri_list_s::opt_closing"]
        [::std::mem::offset_of!(cleri_list_s, opt_closing) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pcre2_real_code_8 {
    _unused: [u8; 0],
}
pub type pcre2_code_8 = pcre2_real_code_8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pcre2_real_match_data_8 {
    _unused: [u8; 0],
}
pub type pcre2_match_data_8 = pcre2_real_match_data_8;
pub type cleri_regex_t = cleri_regex_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_regex_s {
    pub regex: *mut pcre2_code_8,
    pub match_data: *mut pcre2_match_data_8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_regex_s"][::std::mem::size_of::<cleri_regex_s>() - 16usize];
    ["Alignment of cleri_regex_s"][::std::mem::align_of::<cleri_regex_s>() - 8usize];
    ["Offset of field: cleri_regex_s::regex"]
        [::std::mem::offset_of!(cleri_regex_s, regex) - 0usize];
    ["Offset of field: cleri_regex_s::match_data"]
        [::std::mem::offset_of!(cleri_regex_s, match_data) - 8usize];
};
pub type cleri_repeat_t = cleri_repeat_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_repeat_s {
    pub cl_obj: *mut cleri_t,
    pub min: usize,
    pub max: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_repeat_s"][::std::mem::size_of::<cleri_repeat_s>() - 24usize];
    ["Alignment of cleri_repeat_s"][::std::mem::align_of::<cleri_repeat_s>() - 8usize];
    ["Offset of field: cleri_repeat_s::cl_obj"]
        [::std::mem::offset_of!(cleri_repeat_s, cl_obj) - 0usize];
    ["Offset of field: cleri_repeat_s::min"][::std::mem::offset_of!(cleri_repeat_s, min) - 8usize];
    ["Offset of field: cleri_repeat_s::max"][::std::mem::offset_of!(cleri_repeat_s, max) - 16usize];
};
pub type cleri_token_t = cleri_token_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_token_s {
    pub token: *const ::std::os::raw::c_char,
    pub len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_token_s"][::std::mem::size_of::<cleri_token_s>() - 16usize];
    ["Alignment of cleri_token_s"][::std::mem::align_of::<cleri_token_s>() - 8usize];
    ["Offset of field: cleri_token_s::token"]
        [::std::mem::offset_of!(cleri_token_s, token) - 0usize];
    ["Offset of field: cleri_token_s::len"][::std::mem::offset_of!(cleri_token_s, len) - 8usize];
};
pub type cleri_tlist_t = cleri_tlist_s;
pub type cleri_tokens_t = cleri_tokens_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_tlist_s {
    pub token: *const ::std::os::raw::c_char,
    pub len: usize,
    pub next: *mut cleri_tlist_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_tlist_s"][::std::mem::size_of::<cleri_tlist_s>() - 24usize];
    ["Alignment of cleri_tlist_s"][::std::mem::align_of::<cleri_tlist_s>() - 8usize];
    ["Offset of field: cleri_tlist_s::token"]
        [::std::mem::offset_of!(cleri_tlist_s, token) - 0usize];
    ["Offset of field: cleri_tlist_s::len"][::std::mem::offset_of!(cleri_tlist_s, len) - 8usize];
    ["Offset of field: cleri_tlist_s::next"][::std::mem::offset_of!(cleri_tlist_s, next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_tokens_s {
    pub tokens: *mut ::std::os::raw::c_char,
    pub spaced: *mut ::std::os::raw::c_char,
    pub tlist: *mut cleri_tlist_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_tokens_s"][::std::mem::size_of::<cleri_tokens_s>() - 24usize];
    ["Alignment of cleri_tokens_s"][::std::mem::align_of::<cleri_tokens_s>() - 8usize];
    ["Offset of field: cleri_tokens_s::tokens"]
        [::std::mem::offset_of!(cleri_tokens_s, tokens) - 0usize];
    ["Offset of field: cleri_tokens_s::spaced"]
        [::std::mem::offset_of!(cleri_tokens_s, spaced) - 8usize];
    ["Offset of field: cleri_tokens_s::tlist"]
        [::std::mem::offset_of!(cleri_tokens_s, tlist) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_grammar_s {
    pub start: *mut cleri_t,
    pub re_keywords: *mut pcre2_code_8,
    pub match_data: *mut pcre2_match_data_8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_grammar_s"][::std::mem::size_of::<cleri_grammar_s>() - 24usize];
    ["Alignment of cleri_grammar_s"][::std::mem::align_of::<cleri_grammar_s>() - 8usize];
    ["Offset of field: cleri_grammar_s::start"]
        [::std::mem::offset_of!(cleri_grammar_s, start) - 0usize];
    ["Offset of field: cleri_grammar_s::re_keywords"]
        [::std::mem::offset_of!(cleri_grammar_s, re_keywords) - 8usize];
    ["Offset of field: cleri_grammar_s::match_data"]
        [::std::mem::offset_of!(cleri_grammar_s, match_data) - 16usize];
};
pub type cleri_node_t = cleri_node_s;
pub type cleri_children_t = cleri_children_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_children_s {
    pub node: *mut cleri_node_t,
    pub next: *mut cleri_children_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_children_s"][::std::mem::size_of::<cleri_children_s>() - 16usize];
    ["Alignment of cleri_children_s"][::std::mem::align_of::<cleri_children_s>() - 8usize];
    ["Offset of field: cleri_children_s::node"]
        [::std::mem::offset_of!(cleri_children_s, node) - 0usize];
    ["Offset of field: cleri_children_s::next"]
        [::std::mem::offset_of!(cleri_children_s, next) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_node_s {
    pub str_: *const ::std::os::raw::c_char,
    pub len: usize,
    pub cl_obj: *mut cleri_t,
    pub children: *mut cleri_children_t,
    pub data: *mut ::std::os::raw::c_void,
    pub ref_: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_node_s"][::std::mem::size_of::<cleri_node_s>() - 48usize];
    ["Alignment of cleri_node_s"][::std::mem::align_of::<cleri_node_s>() - 8usize];
    ["Offset of field: cleri_node_s::str_"][::std::mem::offset_of!(cleri_node_s, str_) - 0usize];
    ["Offset of field: cleri_node_s::len"][::std::mem::offset_of!(cleri_node_s, len) - 8usize];
    ["Offset of field: cleri_node_s::cl_obj"]
        [::std::mem::offset_of!(cleri_node_s, cl_obj) - 16usize];
    ["Offset of field: cleri_node_s::children"]
        [::std::mem::offset_of!(cleri_node_s, children) - 24usize];
    ["Offset of field: cleri_node_s::data"][::std::mem::offset_of!(cleri_node_s, data) - 32usize];
    ["Offset of field: cleri_node_s::ref_"][::std::mem::offset_of!(cleri_node_s, ref_) - 40usize];
};
pub type cleri_rule_tested_t = cleri_rule_tested_s;
pub type cleri_rule_store_t = cleri_rule_store_s;
pub type cleri_rule_t = cleri_rule_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_rule_tested_s {
    pub str_: *const ::std::os::raw::c_char,
    pub node: *mut cleri_node_t,
    pub next: *mut cleri_rule_tested_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_rule_tested_s"][::std::mem::size_of::<cleri_rule_tested_s>() - 24usize];
    ["Alignment of cleri_rule_tested_s"][::std::mem::align_of::<cleri_rule_tested_s>() - 8usize];
    ["Offset of field: cleri_rule_tested_s::str_"]
        [::std::mem::offset_of!(cleri_rule_tested_s, str_) - 0usize];
    ["Offset of field: cleri_rule_tested_s::node"]
        [::std::mem::offset_of!(cleri_rule_tested_s, node) - 8usize];
    ["Offset of field: cleri_rule_tested_s::next"]
        [::std::mem::offset_of!(cleri_rule_tested_s, next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_rule_store_s {
    pub tested: *mut cleri_rule_tested_t,
    pub root_obj: *mut cleri_t,
    pub depth: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_rule_store_s"][::std::mem::size_of::<cleri_rule_store_s>() - 24usize];
    ["Alignment of cleri_rule_store_s"][::std::mem::align_of::<cleri_rule_store_s>() - 8usize];
    ["Offset of field: cleri_rule_store_s::tested"]
        [::std::mem::offset_of!(cleri_rule_store_s, tested) - 0usize];
    ["Offset of field: cleri_rule_store_s::root_obj"]
        [::std::mem::offset_of!(cleri_rule_store_s, root_obj) - 8usize];
    ["Offset of field: cleri_rule_store_s::depth"]
        [::std::mem::offset_of!(cleri_rule_store_s, depth) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_rule_s {
    pub cl_obj: *mut cleri_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_rule_s"][::std::mem::size_of::<cleri_rule_s>() - 8usize];
    ["Alignment of cleri_rule_s"][::std::mem::align_of::<cleri_rule_s>() - 8usize];
    ["Offset of field: cleri_rule_s::cl_obj"]
        [::std::mem::offset_of!(cleri_rule_s, cl_obj) - 0usize];
};
pub type cleri_prio_t = cleri_prio_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_prio_s {
    pub olist: *mut cleri_olist_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_prio_s"][::std::mem::size_of::<cleri_prio_s>() - 8usize];
    ["Alignment of cleri_prio_s"][::std::mem::align_of::<cleri_prio_s>() - 8usize];
    ["Offset of field: cleri_prio_s::olist"][::std::mem::offset_of!(cleri_prio_s, olist) - 0usize];
};
pub type cleri_parse_t = cleri_parse_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cleri_parse_s {
    pub is_valid: ::std::os::raw::c_int,
    pub flags: ::std::os::raw::c_int,
    pub pos: usize,
    pub str_: *const ::std::os::raw::c_char,
    pub tree: *mut cleri_node_t,
    pub expect: *const cleri_olist_t,
    pub expecting: *mut cleri_expecting_t,
    pub re_keywords: *mut pcre2_code_8,
    pub match_data: *mut pcre2_match_data_8,
    pub kwcache: *mut u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_parse_s"][::std::mem::size_of::<cleri_parse_s>() - 72usize];
    ["Alignment of cleri_parse_s"][::std::mem::align_of::<cleri_parse_s>() - 8usize];
    ["Offset of field: cleri_parse_s::is_valid"]
        [::std::mem::offset_of!(cleri_parse_s, is_valid) - 0usize];
    ["Offset of field: cleri_parse_s::flags"]
        [::std::mem::offset_of!(cleri_parse_s, flags) - 4usize];
    ["Offset of field: cleri_parse_s::pos"][::std::mem::offset_of!(cleri_parse_s, pos) - 8usize];
    ["Offset of field: cleri_parse_s::str_"][::std::mem::offset_of!(cleri_parse_s, str_) - 16usize];
    ["Offset of field: cleri_parse_s::tree"][::std::mem::offset_of!(cleri_parse_s, tree) - 24usize];
    ["Offset of field: cleri_parse_s::expect"]
        [::std::mem::offset_of!(cleri_parse_s, expect) - 32usize];
    ["Offset of field: cleri_parse_s::expecting"]
        [::std::mem::offset_of!(cleri_parse_s, expecting) - 40usize];
    ["Offset of field: cleri_parse_s::re_keywords"]
        [::std::mem::offset_of!(cleri_parse_s, re_keywords) - 48usize];
    ["Offset of field: cleri_parse_s::match_data"]
        [::std::mem::offset_of!(cleri_parse_s, match_data) - 56usize];
    ["Offset of field: cleri_parse_s::kwcache"]
        [::std::mem::offset_of!(cleri_parse_s, kwcache) - 64usize];
};
pub type cleri_via_t = cleri_u;
pub type cleri_free_object_t = ::std::option::Option<unsafe extern "C" fn(arg1: *mut cleri_t)>;
pub type cleri_parse_object_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut cleri_parse_t,
        arg2: *mut cleri_node_t,
        arg3: *mut cleri_t,
        arg4: *mut cleri_rule_store_t,
    ) -> *mut cleri_node_t,
>;
pub const cleri_e_CLERI_TP_SEQUENCE: cleri_e = 0;
pub const cleri_e_CLERI_TP_OPTIONAL: cleri_e = 1;
pub const cleri_e_CLERI_TP_CHOICE: cleri_e = 2;
pub const cleri_e_CLERI_TP_LIST: cleri_e = 3;
pub const cleri_e_CLERI_TP_REPEAT: cleri_e = 4;
pub const cleri_e_CLERI_TP_PRIO: cleri_e = 5;
pub const cleri_e_CLERI_TP_RULE: cleri_e = 6;
pub const cleri_e_CLERI_TP_THIS: cleri_e = 7;
pub const cleri_e_CLERI_TP_KEYWORD: cleri_e = 8;
pub const cleri_e_CLERI_TP_TOKEN: cleri_e = 9;
pub const cleri_e_CLERI_TP_TOKENS: cleri_e = 10;
pub const cleri_e_CLERI_TP_REGEX: cleri_e = 11;
pub const cleri_e_CLERI_TP_REF: cleri_e = 12;
pub const cleri_e_CLERI_TP_END_OF_STATEMENT: cleri_e = 13;
pub type cleri_e = ::std::os::raw::c_uint;
pub use self::cleri_e as cleri_tp;
#[repr(C)]
#[derive(Copy, Clone)]
pub union cleri_u {
    pub keyword: *mut cleri_keyword_t,
    pub sequence: *mut cleri_sequence_t,
    pub optional: *mut cleri_optional_t,
    pub choice: *mut cleri_choice_t,
    pub regex: *mut cleri_regex_t,
    pub list: *mut cleri_list_t,
    pub repeat: *mut cleri_repeat_t,
    pub token: *mut cleri_token_t,
    pub tokens: *mut cleri_tokens_t,
    pub prio: *mut cleri_prio_t,
    pub rule: *mut cleri_rule_t,
    pub dup: *mut cleri_dup_t,
    pub dummy: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_u"][::std::mem::size_of::<cleri_u>() - 8usize];
    ["Alignment of cleri_u"][::std::mem::align_of::<cleri_u>() - 8usize];
    ["Offset of field: cleri_u::keyword"][::std::mem::offset_of!(cleri_u, keyword) - 0usize];
    ["Offset of field: cleri_u::sequence"][::std::mem::offset_of!(cleri_u, sequence) - 0usize];
    ["Offset of field: cleri_u::optional"][::std::mem::offset_of!(cleri_u, optional) - 0usize];
    ["Offset of field: cleri_u::choice"][::std::mem::offset_of!(cleri_u, choice) - 0usize];
    ["Offset of field: cleri_u::regex"][::std::mem::offset_of!(cleri_u, regex) - 0usize];
    ["Offset of field: cleri_u::list"][::std::mem::offset_of!(cleri_u, list) - 0usize];
    ["Offset of field: cleri_u::repeat"][::std::mem::offset_of!(cleri_u, repeat) - 0usize];
    ["Offset of field: cleri_u::token"][::std::mem::offset_of!(cleri_u, token) - 0usize];
    ["Offset of field: cleri_u::tokens"][::std::mem::offset_of!(cleri_u, tokens) - 0usize];
    ["Offset of field: cleri_u::prio"][::std::mem::offset_of!(cleri_u, prio) - 0usize];
    ["Offset of field: cleri_u::rule"][::std::mem::offset_of!(cleri_u, rule) - 0usize];
    ["Offset of field: cleri_u::dup"][::std::mem::offset_of!(cleri_u, dup) - 0usize];
    ["Offset of field: cleri_u::dummy"][::std::mem::offset_of!(cleri_u, dummy) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cleri_s {
    pub gid: u32,
    pub ref_: u32,
    pub free_object: cleri_free_object_t,
    pub parse_object: cleri_parse_object_t,
    pub tp: cleri_tp,
    pub via: cleri_via_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_s"][::std::mem::size_of::<cleri_s>() - 40usize];
    ["Alignment of cleri_s"][::std::mem::align_of::<cleri_s>() - 8usize];
    ["Offset of field: cleri_s::gid"][::std::mem::offset_of!(cleri_s, gid) - 0usize];
    ["Offset of field: cleri_s::ref_"][::std::mem::offset_of!(cleri_s, ref_) - 4usize];
    ["Offset of field: cleri_s::free_object"]
        [::std::mem::offset_of!(cleri_s, free_object) - 8usize];
    ["Offset of field: cleri_s::parse_object"]
        [::std::mem::offset_of!(cleri_s, parse_object) - 16usize];
    ["Offset of field: cleri_s::tp"][::std::mem::offset_of!(cleri_s, tp) - 24usize];
    ["Offset of field: cleri_s::via"][::std::mem::offset_of!(cleri_s, via) - 32usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cleri_dup_s {
    pub gid: u32,
    pub ref_: u32,
    pub free_object: cleri_free_object_t,
    pub parse_object: cleri_parse_object_t,
    pub tp: cleri_tp,
    pub via: cleri_via_t,
    pub dup: *mut cleri_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cleri_dup_s"][::std::mem::size_of::<cleri_dup_s>() - 48usize];
    ["Alignment of cleri_dup_s"][::std::mem::align_of::<cleri_dup_s>() - 8usize];
    ["Offset of field: cleri_dup_s::gid"][::std::mem::offset_of!(cleri_dup_s, gid) - 0usize];
    ["Offset of field: cleri_dup_s::ref_"][::std::mem::offset_of!(cleri_dup_s, ref_) - 4usize];
    ["Offset of field: cleri_dup_s::free_object"]
        [::std::mem::offset_of!(cleri_dup_s, free_object) - 8usize];
    ["Offset of field: cleri_dup_s::parse_object"]
        [::std::mem::offset_of!(cleri_dup_s, parse_object) - 16usize];
    ["Offset of field: cleri_dup_s::tp"][::std::mem::offset_of!(cleri_dup_s, tp) - 24usize];
    ["Offset of field: cleri_dup_s::via"][::std::mem::offset_of!(cleri_dup_s, via) - 32usize];
    ["Offset of field: cleri_dup_s::dup"][::std::mem::offset_of!(cleri_dup_s, dup) - 40usize];
};
unsafe extern "C" {
    pub fn compile_extxyz_kv_grammar() -> *mut cleri_grammar_t;
}
